### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by EricLyn77** [b4l/imagination#1]
Hi, Thanks for your amazing work. I'm wondering if you could provide a link to the dataset and pre-trained model. That would be great.

**Comment by b4l** [comment]
Hi, the aerial imagery is [SWISSIMAGE](https://www.swisstopo.admin.ch/en/geodata/images/ortho/swissimage10.html) and the roads are from [swissTLM3D](https://www.swisstopo.admin.ch/en/geodata/landscape/tlm3d.html). Unfortunately I don't have any model checkpoints. This repository is just a dump of what we worked on during a hackaton some time ago.

**Comment by EricLyn77** [comment]
Thanks for you reply
